col.names <- read.table("household_power_consumption.txt", sep = ";", nrows = 1, colClasses = "character")
household <- read.table("household_power_consumption.txt", header = FALSE, sep =";", skip = 66637, nrows = 2880, col.names = col.names[1,], colClasses = c("character", "character","numeric","numeric","numeric","numeric","numeric","numeric","numeric"), na.strings = "?")
datetime <- strptime(paste(household$Date, household$Time), format = "%d/%m/%Y %H:%M:%S")
household <- cbind(household, datetime)
png("plot4.png")
par(mfrow = c(2,2))
plot(household$datetime, household$Global_active_power, type = "l", ylab = "Global Active Power", xlab = "")
plot(household$datetime, household$Voltage, type = "l", ylab = "Voltage", xlab = "datetime")
plot(household$datetime, household$Sub_metering_1, ylab = "Energy sub metering", xlab = "", type = "n")
lines(household$datetime, household$Sub_metering_1)
lines(household$datetime, household$Sub_metering_2, col = "red")
lines(household$datetime, household$Sub_metering_3, col = "blue")
legend("topright", legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), col = c("black", "red", "blue"), lwd = 1, bty = "n")
plot(household$datetime, household$Global_reactive_power, type = "l", ylab = "Global_reactive_power", xlab = "datetime")
dev.off()
